project_id = "dlitdjbmqpsdmhrbluak"

[functions.accept-invitation]
verify_jwt = false

[functions.activate-user-account]
verify_jwt = false

[functions.check-expired-attendance-links]
verify_jwt = false

[functions.cleanup-auth-users]
verify_jwt = false

[functions.create-establishment]
verify_jwt = false

[functions.generate-attendance-sheets]
verify_jwt = false

[functions.invite-tutor-native]
verify_jwt = false

[functions.invite-user-native]
verify_jwt = false

[functions.manage-attendance-timing]
verify_jwt = false

[functions.process-scheduled-messages]
verify_jwt = false

[functions.resend-invitation-native]
verify_jwt = false

[functions.reset-password-native]
verify_jwt = false

[functions.send-email-brevo]
verify_jwt = false

[functions.send-message]
verify_jwt = false

[functions.send-notification-emails]
verify_jwt = false

[functions.send-signature-link]
verify_jwt = false

[functions.validate-activation-token]
verify_jwt = false

[functions.send-contact-form]
verify_jwt = false

[functions.invite-super-admin]
verify_jwt = false

[functions.blog-ai]
verify_jwt = false

[functions.social-media]
verify_jwt = false

[functions.content-autopilot]
verify_jwt = false

[functions.linkedin-oauth]
verify_jwt = false
